language: ruby
rvm:
  - 2.4.1
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux32.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.18.0-linux32.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
cache: bundler
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    target_branch: gh-pages
