$secrets = {apikey: ENV['APIKEY'],
            useremail: ENV['TESTUSER'],
            egurl: ENV['EGURL'],
            testclientfirst: ENV['TESTCLIENTFIRST'],
            testclientlast: ENV['TESTCLIENTLAST'],
            testclientdob: ENV['TESTCLIENTDOB'],
            teststate: ENV['TESTSTATE'],
            docketnums: [ENV['TESTDOCKET1'],
                         ENV['TESTDOCKET2'],
                         ENV['TESTDOCKET3'],
                         ENV['TESTDOCKET4'],
                         ENV['TESTDOCKET5']],
            browseruseremail: ENV['BROWSERUSEREMAIL'],
            browseruserpass: ENV['BROWSERUSERPASS'],
            browserusername: ENV['BROWSERUSERNAME']}
